### PR TITLE
fix: better OG image design & filtering events for months

### LINKED ISSUE #84: Verify the event image link
Don't let the users enter random links on event image input. Make sure that it's a valid url and is an img url.

### LINKED ISSUE #90: Sort the events in the /about timeline with latest first
currently the opposite

### PR DESCRIPTION
**Pull request by nagarajpandith**
# Pull Request

## 📋 Description  
- this implements filtering logic for top 3 events in OG image
  - past month (endDate < now): selects events from that month. priority is given to dk24 org events. secondary sort is chronological by date.
  - current month: selects upcoming events (startDate >= now) first. if <3 upcoming events, fills remaining slots with most recent past events (startDate < now) from this month. this whole list is then chronologically sorted by date.
  - future month (startdate > now): selects top 3 events sorted chronologically by startDate.
- OG image design is improved with more breathing space and some ui polishes [check screenshots](#📝-Additional-Notes)
- fixes #84 - verifying imageurl on frontend using img constructor success or error (cant rely on zod path validation since image paths can end without extensions - explained on #84)
- fixes #90 - sort events by latest first in timeline section of event page
- update finiteloop club's new website link

## 🔄 Type of Change  

- [x] Bug fix  
- [ ] New feature  
- [x] Refactor  
- [ ] Documentation  

## 🧪 Testing  
Lint, type checks and build passed
Locally tested with mock events data

## 📝 Additional Notes  
design changes in OG image
- cards & text are made bigger for better readability on phones
- utilised extra space on the bottom my moving footer text above
- events are marked with "upcoming" and "completed"
- dk24 org events are slightly highlighted with brand coloured border

**examples**
1. [current month] jan-2026 - we get 2 upcoming events and the extra slot is filled with one past event and the whole list is chronologically sorted. 17th jan is past event and is marked with "completed". rest two are marked as "upcoming"
image
2. [future month] feb-2026 - top 3 events in that month sorted by startdate are taken. first 2 events are hosted by dk24 org and hence marked with green border and a small inobtrusive badge "BY DK24"
image
3. [past month] dec-2025 - dk24 hosted event is given more priority despite the date. rest 2 events are sorted chronologically by date.
image
4. [no events fallback]
image

#84 - form validation on blur and on submit

https://github.com/user-attachments/assets/40ccbeb4-52a4-442e-b38e-dfb01b6e2867

### CODE REVIEW

File: src/constants/member-colleges.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ export const communities: Community[] = [
         email: "nandan@finiteloop.club",
       },
     ],
-    website: "https://www.finiteloop.co.in",
+    website: "https://www.finiteloop.club",
```
Comment (gaureshpai) [inline src/constants/member-colleges.ts]: This site can’t be reached

www.finiteloop.club took too long to respond.
